"""create registrations

Revision ID: a43d8ca84af3
Revises: 69372caad60f
Create Date: 2026-09-23 11:44:04.481921

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a43d8ca84af3'
down_revision: str | Sequence[str] | None = '69372caad60f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ticket_token', sa.String(length=36), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'email', name='uq_registrations_event_email')
    )
    op.create_index(
        op.f('ix_registrations_email'), 'registrations', ['email'], unique=False
    )
    op.create_index(
        op.f('ix_registrations_event_id'),
        'registrations',
        ['event_id'],
        unique=False,
    )
    op.create_index(
        op.f('ix_registrations_ticket_token'),
        'registrations',
        ['ticket_token'],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registrations_ticket_token'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_event_id'), table_name='registrations')
    op.drop_index(op.f('ix_registrations_email'), table_name='registrations')
    op.drop_table('registrations')
    # ### end Alembic commands ###
